Python/field_up/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

Python/field_up/field_up/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('site_app.urls')),
    path('', include('accounts.urls')), 
] 

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Python/field_up/accounts/models.py
from inspect import isframe
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

# Create your models here.
class CustomUser(AbstractUser):
    class Meta:
        verbose_name_plural = 'CustomUser'


class Category(models.Model):
    name = models.CharField(max_length=256, help_text='カテゴリー名')
    create_date = models.DateTimeField(auto_now_add=True, help_text='作成日')
    update_date = models.DateTimeField(auto_now=True, help_text='更新日')

    def __str__(self):
        return self.name


class Main(models.Model):
    category = models.ForeignKey(Category, related_name='Mains', on_delete=models.CASCADE, help_text='カテゴリーID')
    thumbnail = models.ImageField(blank=True, null=True)
    summary_text = models.TextField(help_text='サマリーテキスト')
    iframe_code = models.TextField(help_text='iframeコード')
    create_date = models.DateTimeField(auto_now_add=True, help_text='作成日')
    update_date = models.DateTimeField(auto_now=True, help_text='更新日')
    
    def __str__(self):
        self.iframe_code.replace("embed/","watch?v=")
        return str(self.id)

    def iframe(text):
        text = text.replace("embed/","watch?v=")
        return text

Python/field_up/accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    "ログオンフォーム"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

Python/field_up/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)
from django.views import generic
from django.urls import reverse
from django.urls import reverse_lazy
from .forms import LoginForm
from . import models

# Create your views here.

# コンテンツ管理画面
class LoginView(LoginView):
    template_name = "login.html"
    form_class = LoginForm

class IndexView(LoginRequiredMixin, generic.ListView):
    model = models.Main
    context_object_name = "main_list"
    template_name = "index.html"
    paginate_by = 5

class CreateView(LoginRequiredMixin, generic.CreateView):
    model = models.Main
    fields = ("category","thumbnail","summary_text","iframe_code")
    template_name = "form.html"
    success_url = reverse_lazy("accounts:index")

class UpdateView(LoginRequiredMixin, generic.UpdateView):
    fields = ("category","thumbnail","summary_text","iframe_code")
    model = models.Main
    template_name = "form.html"
    success_url = reverse_lazy("accounts:index")

class DeleteView(generic.DeleteView):
    model = models.Main
    template_name = "delete.html"
    success_url = reverse_lazy("accounts:index")

class Logout(LoginRequiredMixin, LogoutView):
    template_name = "login.html"

Python/field_up/accounts/templates/delete.html
<h1>本当に削除しますか?</h1>
<form method="post">
  {% csrf_token %}
  <p>{{ main.category }}</p>
  <p>{{ main.thumbnail }}</p>
  <p>{{ main.summary_text }}</p>
  <p>{{ main.iframe_code }}</p>
  <input type="submit" class="btn btn-danger" value="削除">
  <a href="{% url 'accounts:update' pk=main.pk %} ">キャンセル</a>
</form>

Python/field_up/accounts/templates/form.html
{% extends 'site_app/base_1.html' %}

{% load static %}

{% block title %}入力画面{% endblock %}

{% block head %}
    <meta name="description" content="">
    <meta name="keywords" content="">
{% endblock %}

{% block contents %}

<div class="container content content_form">
    <h1 class="text-center">システム事業<br>コンテンツ入力画面</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <!-- <div class="btn-group">
            <input type="text" class="form-control" style="width:200px;"  placeholder="category">
            <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              Action
            </button>
            <ul class="dropdown-menu">
              <li>Python</li>
              <li>VBA</li>
              <li>Swift</li>
              <li>Kotlin</li>
              <li>PHP</li>
            </ul>
        </div> -->
        <!-- <div class="mt-5 d-flex align-items-center">
            <p>カテゴリー</p>
            <select name="category" id="">
                <option value="2">Python</option>
            </select>
        </div>
        <div class="mt-5 d-flex align-items-center">
            <p>サムネイル</p>
            <input class="d-block m-4" name="thumbnail">
        </div>
        <div class="mt-5 d-flex align-items-center">
            <p>サマリーテキスト</p>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="summary_text"></textarea>
        </div>
    
        <div class="mt-5 d-flex align-items-center">
            <p>iframeコード</p>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="iframe_code"></textarea>
        </div> -->
    
        <!-- <div class="mt-5 d-flex align-items-center">
        
            <input type="password" class="form-control" style="width:200px;"  placeholder="password">
            <button type="submit" class="btn btn-primary m-4">ログイン</button>
        </div> -->
        <button type="button" class="btn btn-primary m-4" onclick="location.href='{% url 'accounts:index' %}'">戻る</button>
        <button type="submit" class="btn btn-primary m-4">登録</button>
        
    </form>
    
</div>

{% endblock %}

Python/field_up/accounts/templates/index.html
{% extends 'site_app/base_1.html' %}

{% load static %}

{% block title %}コンテンツ管理画面{% endblock %}

{% block head %}
    <meta name="description" content="">
    <meta name="keywords" content="">
{% endblock %}

{% block contents %}

<div class="container content mb-5">
    <h1 class="text-center">システム事業<br>コンテンツ管理画面</h1>
    <button onclick="location.href='{% url 'accounts:create' %}'" class="btn btn-primary m-4">新規コンテンツ追加</button>
    <button onclick="location.href='{% url 'accounts:logout' %}'" class="btn btn-primary m-4">ログアウト</button>

    <table class="table table-hover">
        <tr class="bg-info">
            <th>カテゴリ</th>
            <th>サムネ画像</th>
            <th>サマリーテキスト</th>
            <th>iframe</th>
            <th></th>
            <th></th>
        </tr>
        {% for main in main_list %}
        <tr>
            <td>{{ main.category }}</td>
            <td>{{ main.thumbnail }}</td>
            <td>{{ main.summary_text }}</td>
            <td>{{ main.iframe_code }}</td>
            <td><button onclick="location.href='{% url 'accounts:update' pk=main.pk %}'" class="btn btn-primary m-4">編集</button></td>
            <td><button onclick="location.href='{% url 'accounts:delete' pk=main.pk %}'" type="button" class="btn btn-danger m-4">削除</button></td>
        </tr>
        {% endfor %}
    </table>

    <div class="row p-3">
        <div class="col-5"></div>
        <div class="col-4">
            <div class="pagination">
                {% for num in page_obj.paginator.page_range %}
                <input id="dot-{{num}}" type="radio" name="dots" class="dots" data-num="{{ num }}">
                <label for="dot-{{num}}"></label>
                {% endfor %}
                <div class="pacman"></div>
            </div>
            <div class="col-3"></div>
        </div>
    </div>

</div>

{% endblock %}

Python/field_up/accounts/templates/login.html
{% extends 'site_app/base_1.html' %}

{% load static %}

{% block title %}ログイン画面{% endblock %}

{% block head %}
    <meta name="description" content="">
    <meta name="keywords" content="">
{% endblock %}

{% block active_singup %}active{% endblock %}

{% block contents %}

{% comment %} user:ueda password:gbw21ueda {% endcomment %}

<div class="container content">
    <h1 class="text-center">システム事業<br>コンテンツログイン画面</h1>

    <div class="login-box-body mt-2">
        <form action="" method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group has-feedback mt-3 mb-3">
                {{ field }}
            </div>
            {% endfor %}
            <div class="row">
  
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                    <p>{{ error }}</p>
                </div>
                {% endfor %}

                <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">ログオン</button>
                </div>
            </div>
        </form>
      </div>
  

    {% comment %} <form method="post" >
        {% csrf_token %}
        {{form.as_p}}

        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}">
        {% endif %}

        <button type="submit" class="btn btn-primary m-4">ログイン</button>

    </form> {% endcomment %}
    
</div>

{% endblock %}