Python/field_up/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

Python/field_up/field_up/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('site_app.urls')),
    path('', include('accounts.urls')), 
] 

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Python/field_up/site_app/urls.py
from django.urls import path
from . import views

app_name = 'site_app'
urlpatterns = [
    path('',views.IndexView.as_view(), name='top'),
    path('company/', views.CompanyView.as_view(), name='company'),
    path('news/', views.NewsView.as_view(), name='news'),
    path('appeal/', views.AppealView.as_view(), name='appeal'),
    
    path('contacts_faq/', views.ContactsFaqView.as_view(), name='contacts_faq'),
    path('contact_result/', views.ContactResultView.as_view(), name='contact_result'),

    path('example/', views.ExampleView.as_view(), name='example'),

    path('lang/', views.langView.as_view(), name='lang'),
    
    path('vba/', views.VbaView.as_view(), name='vba'),
    path('python/', views.PythonView.as_view(), name='python'),
    path('java/', views.JavaView.as_view(), name='java'),
    path('powerautomate/', views.PowerAutomateView.as_view(), name='powerautomate'),
    path('kotlin/', views.KotlinView.as_view(), name='kotlin'),
    path('css/', views.CssView.as_view(), name='css'),
    path('php/', views.PhpView.as_view(), name='php'),
    path('swift/', views.SwiftView.as_view(), name='swift'),
    path('html/', views.HtmlView.as_view(), name='html'),
    path('javascript/', views.JavaScriptView.as_view(), name='javascript'),
    path('go/', views.GoView.as_view(), name='go'),
    path('c_sharp/', views.CsharpView.as_view(), name='c_sharp'),
    path('swift/', views.SwiftView.as_view(), name='swift'),
]

Python/field_up/site_app/models.py
from django.db import models

# Create your models here.

Python/field_up/site_app/forms.py
from django import forms
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse

class ContactForm(forms.Form):
    name = forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': "お名前",
        }),
    )
    email = forms.EmailField(
        label='',
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': "メールアドレス",
        }),
    )
    message = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': "お問い合わせ内容",
        }),
    )

    def send_email(self):
        subject = "お問い合わせ"
        message = self.cleaned_data['message']
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        from_email = '{name} <{email}>'.format(name=name, email=email)
        recipient_list = [settings.EMAIL_HOST_USER]  # 受信者リスト
        try:
            send_mail(subject, message, from_email, recipient_list)
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

Python/field_up/site_app/views.py
# from lib2to3.pgen2.pgen import generate_grammar
from django.shortcuts import render
from django.views import generic
from .forms import ContactForm
from django.urls import reverse_lazy
from accounts.models import Main
# from django.contrib import messages


# Create your views here.

# TOP
class IndexView(generic.TemplateView):
    template_name = "site_app/top.html"

# Company
class CompanyView(generic.TemplateView):
    template_name = "site_app/company.html"

# NEWS
class NewsView(generic.TemplateView):
    template_name = "site_app/news.html"

# Contacts & FAQ
class ContactsFaqView(generic.FormView):
    template_name = "site_app/contacts_faq.html"
    form_class = ContactForm
    success_url = reverse_lazy('site_app:contact_result')

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)

# 送信完了ページ
class ContactResultView(generic.TemplateView):
    template_name = "site_app/contact_result.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['success'] = "お問い合わせありがとうございます。折り返しご連絡いたします。"
        return context

# デジタルの魅力
class AppealView(generic.TemplateView):
    template_name = "site_app/appeal.html"

# システム開発とは
class ExampleView(generic.TemplateView):
    template_name = "site_app/example.html"

class Example1View(generic.TemplateView):
    template_name = "site_app/examples/example-1.html"

class Example2View(generic.TemplateView):
    template_name = "site_app/examples/example-2.html"

class Example3View(generic.TemplateView):
    template_name = "site_app/examples/example-3.html"


# プログラミングとは
class langView(generic.TemplateView):
    template_name = "site_app/lang.html"

class VbaView(generic.ListView):
    template_name = "site_app/languages/vba.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 1)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset

class PythonView(generic.ListView):
    template_name = "site_app/languages/python.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 2)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset

class JavaView(generic.ListView):
    template_name = "site_app/languages/java.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 3)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset

class PowerAutomateView(generic.ListView):
    template_name = "site_app/languages/powerautomate.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 4)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset

class KotlinView(generic.ListView):
    template_name = "site_app/languages/kotlin.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 5)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset

class CssView(generic.ListView):
    template_name = "site_app/languages/css.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 6)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset

class PhpView(generic.ListView):
    template_name = "site_app/languages/php.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 7)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset

class SwiftView(generic.ListView):
    template_name = "site_app/languages/swift.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 8)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset

class HtmlView(generic.ListView):
    template_name = "site_app/languages/html.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 9)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset

class JavaScriptView(generic.ListView):
    template_name = "site_app/languages/javascript.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 10)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset

class GoView(generic.ListView):
    template_name = "site_app/languages/go.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 11)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset

class CsharpView(generic.ListView):
    template_name = "site_app/languages/c_sharp.html"
    model = Main
    context_object_name = "main_list"
    paginate_by = 5
    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        queryset = queryset.filter(category_id = 12)
        for set in queryset:
            set.iframe_code = set.iframe_code.replace("watch?v=","embed/")
        return queryset


Python/field_up/site_app/templates/site_app/base_2.html
{% load static %}
<!DOCTYPE html>
<html lang="jp">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Field-UP">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'site_app/css/layout.css' %}">

    <!-- JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="{% static 'site_app/js/layout.js' %}"></script>
    
    <!-- その他 -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="  crossorigin="anonymous"></script>
    <script src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/5-2-5/js/5-2-5.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    
    <!-- フォト -->
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">
    {% comment %} <link rel="stylesheet" type="text/css" href="http://mplus-fonts.sourceforge.jp/webfonts/general-j/mplus_webfonts.css"> {% endcomment %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@300&family=Noto+Serif+JP&display=swap" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=DotGothic16' rel='stylesheet'>

    <!-- 各種設定 -->
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}

    <!-- ファビコン -->
    <link rel="icon" type="image/png" href="{% static 'site_app/img/ファビコン1.png' %}">

    {% comment %} GA4 {% endcomment %}
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-167968304-8"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-167968304-8');
    </script>

  </head>
  <body>
    <!-- ヘッダー -->
    <header id="header">
      <div class="row bg-1 header-inner pb-3">
        <div class="col-12">
          <a href="{% url 'site_app:top' %}"><img class="m-3 sp-logo" src="{% static 'site_app/img/logo.png' %}" width="350px"></a>
          {% comment %} <video autoplay muted loop src="{% static 'site_app/img/mini_anime.mp4' %}" width="250px" class="float-end anime01"> {% endcomment %}
          <h1 class="title">
            <span>T</span>
            <span>E</span>
            <span>C</span>
            <span>H</span>
            <span>N</span>
            <span>O</span>
            <span>L</span>
            <span>O</span>
            <span>G</span>
            <span>Y</span>
            {% comment %} <span>&nbsp;</span>
            <span>I</span>
            <span>d</span>
            <span>N</span> {% endcomment %}
          </h1>
        </div>

        <div class="openbtn4"><span></span><span></span><span></span></div>

        <div class="hidden-menu row d-none position-fixed vh-100">
          <nav class="nav-2">
            <ul>
              <li class="mb-4"><a href="{% url 'site_app:company' %}">Company</a></li>
              {% comment %} <li class="mb-4"><a href="{% url 'site_app:news' %}">News</a></li> {% endcomment %}
              <li class="mb-4 ps-3 has-child"><a href="#">Content</a>
                <ul>
                  <li class="my-3 ps-3"><a href="{% url 'site_app:appeal' %}">デジタルの魅力</a></li>
                  <li class="pb-3 ps-3 has-child"><a href="{% url 'site_app:example' %}">システム開発</a>
                    <ul>
                      <li class="py-1"><a href="https://www.youtube.com/watch?v=aTx8wclrYVo" target="_blank">映像開発</a></li>
                      <li class="pb-1"><a href="https://field-up.work/demo_room/main.html" target="_blank">VR開発</a></li>
                      <li><a href="https://field-up.work/bound_demo/" target="_blank">簡易ゲーム開発</a></li>
                    </ul>
                  </li>
                  <li class="ps-3 has-child"><a href="{% url 'site_app:lang' %}">プログラミング</a>
                    <ul>
                      <li><a href="{% url 'site_app:vba' %}">VBA</a></li>
                      <li><a href="{% url 'site_app:python' %}">Python</a></li>
                      <li><a href="{% url 'site_app:java' %}">Java</a></li>
                      <li><a href="{% url 'site_app:powerautomate' %}">PowerAutomate</a></li>
                      <li><a href="{% url 'site_app:kotlin' %}">Kotlin</a></li>
                      <li>その他...</li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li><a href="{% url 'site_app:contacts_faq' %}">Contacts & FAQ</a></li>
            </ul>
          </nav>
        </div>
        
      </div>
    </header>

    <div class="mt-3 mb-4">
      <div class="teto">
        <canvas></canvas>
        {% block contents %}{% endblock %}
      </div>
    </div>

  {% comment %} {% block header %}{% endblock %} {% endcomment %}
  <!-- フッター -->
  <footer class="bg-white border-top border-3 border-info">
    {% include 'site_app/footer.html' %}
  </footer>
    {% comment %} ヘッダーアニメーション {% endcomment %}
    <script>
      // ヘッダーアニメ
      const CLASSNAME = "-visible";
      const TIMEOUT = 2500;
      const $target = $(".title");
  
      setInterval(() => {
        $target.addClass(CLASSNAME);
        setTimeout(() => {
          $target.removeClass(CLASSNAME);
        }, TIMEOUT);
      }, TIMEOUT * 2);
    </script>

    {% comment %} 背景アニメ {% endcomment %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r67/three.min.js"></script>
  <script>
    var mouseX = 0,
        mouseY = 0,
        windowHalfX = window.innerWidth / 2,
        windowHalfY = window.innerHeight / 2,
        SEPARATION = 200,
        AMOUNTX = 10,
        AMOUNTY = 10,
        camera,
        scene,
        renderer;
    init();
    animate();

    function init() {
      var container,
          separation = 100,
          amountX = 50,
          amountY = 50,
          particle;
      
      container = document.createElement( 'div' );
      document.body.appendChild( container );
      scene = new THREE.Scene();
      renderer = new THREE.CanvasRenderer({ alpha: true }); // gradient; this can be swapped for WebGLRenderer
      renderer.setSize( window.innerWidth, window.innerHeight );
      container.appendChild( renderer.domElement );
      camera = new THREE.PerspectiveCamera(
        75,
        window.innerWidth / window.innerHeight,
        1,
        10000
      );
      camera.position.z = 100;
      // particles
      var PI2 = Math.PI * 2;
      var material = new THREE.SpriteCanvasMaterial({
        color: 0x0db6ff,
        program: function ( context ) {
          context.beginPath();
          context.arc( 0, 0, 0.5, 0, PI2, true );
          context.fill();
        }
      });
      var geometry = new THREE.Geometry();
      for ( var i = 0; i < 100; i ++ ) {
        particle = new THREE.Sprite( material );
        particle.position.x = Math.random() * 2 - 1;
        particle.position.y = Math.random() * 2 - 1;
        particle.position.z = Math.random() * 2 - 1;
        particle.position.normalize();
        particle.position.multiplyScalar( Math.random() * 10 + 450 );
        particle.scale.x = particle.scale.y = 10;
        scene.add( particle );
        geometry.vertices.push( particle.position );
      }
      // lines
      var line = new THREE.Line( geometry, new THREE.LineBasicMaterial( { color: 0x0db6ff, opacity: 0.3 } ) );
      scene.add( line );
      // mousey
      document.addEventListener( 'mousemove', onDocumentMouseMove, false );
      document.addEventListener( 'touchstart', onDocumentTouchStart, false );
      document.addEventListener( 'touchmove', onDocumentTouchMove, false );
      window.addEventListener( 'resize', onWindowResize, false );
    } // end init();

    function onWindowResize() {
      windowHalfX = window.innerWidth / 2;
      windowHalfY = window.innerHeight / 2;
      camera.aspect = window.innerWidth / window.innerHeight;
      camera.updateProjectionMatrix();
      renderer.setSize( window.innerWidth, window.innerHeight );
    }

    function onDocumentMouseMove(event) {
      mouseX = event.clientX - windowHalfX;
      mouseY = event.clientY - windowHalfY;
    }

    function onDocumentTouchStart( event ) {
      if ( event.touches.length > 1 ) {
        event.preventDefault();
        mouseX = event.touches[ 0 ].pageX - windowHalfX;
        mouseY = event.touches[ 0 ].pageY - windowHalfY;
      }
    }
    function onDocumentTouchMove( event ) {
      if ( event.touches.length == 1 ) {
        event.preventDefault();
        mouseX = event.touches[ 0 ].pageX - windowHalfX;
        mouseY = event.touches[ 0 ].pageY - windowHalfY;
      }
    }
    function animate() {
      requestAnimationFrame( animate );
      render();
    }
    function render() {
      camera.position.x += ( mouseX - camera.position.x ) * .05;
      camera.position.y += ( - mouseY + 200 - camera.position.y ) * .05;
      camera.lookAt( scene.position );
      renderer.render( scene, camera );
    }
  </script>
  
  </body>
</html>

Python/field_up/site_app/templates/site_app/company.html
{% extends 'site_app/base_2.html' %}

{% load static %}

{% block title %}事業概要|Field-UP{% endblock %}

{% block head %}
    <meta name="description" content="Field-UPのシステム事業がどんなことをしているかお伝えします。サイトや、アプリの開発だけでなく、エンジニアの育成やオンライン講座、サーバー周りの業務など幅広く展開しております。システム事業以外にも違った事業も展開しているので是非ご覧ください。">
    <meta name="keywords" content="プログラミング,開発,システム開発,Field-UP,フィールドアップ,FIELD-UP,アプリケーション,アプリ">
{% endblock %}

{% block contents %}

    {% comment %} コンテンツ {% endcomment %}
    <div class="container content">
        <h1 class="text-center right cont-h">Company</h1>
        <div class="row mx-auto">
            <h2>やりたいこと夢を目標、現実へ落とし込んでいくためのプロフェッショナル</h2>
            <div class="row bg-white">
                <div class="col-md-8 mt-2">
                    <p>機械工学、内装業、心理学、システム開発、コンサルティングと複数の業界で今もなお、前線で活躍し続けています</p>
                    <p>だからこそ得られる新しい知見や、技術をそれぞれの現場で生かすことによって新しい発想や、他では思いもつかないような業界シナジーを生み出すことが私たちの強みです</p>
                    <h2>代表の思い</h2>
                    <p>僕は社会的に見て『できる人』という社会人では決してありません。失敗もしますし、物覚えも特別にいいということもないです<br>
                    そんな僕がこうやって事業を続けられてこれているのは『多くの良い仲間』と、野球を昔から続けてきて培った『諦めの悪さ』が僕をココまで成長させてくれました</p>
                    <p>今の事業形態や、僕のスキルはまだまだ途中経過でしかなく、今はまだ手の届く範囲が少なく、お手伝いのできる方々が少ないですが<br>
                    後にはもっと多くの人の力になれるような事業として成長していく予定です。</p>
                    <p>そのために大きな要因として『僕自身の成長 = 事業の成長』だと自覚して、慢心せずに仲間と一緒にスキルアップを続けていきます</p>

                </div>
                <div class="col-md-4 mt-2 mb-2">
                    <img class="d-block mx-auto ro-Y" alt="CEO" src="{% static 'site_app/img/ceo1.jpg' %}" width="100%">
                    <h2 class="text-center">代表 上田敬介</h2>
                </div>

            </div>
            <div class="row mx-auto fadeup">
                <div class="text-center bg-white mt-5 p-3 div00 border border-3 border-info mb-5">
                    <p>会社名：Field-UP</p>
                    <p>所在地：〒114-0011 東京都北区昭和町1-4-7</p>
                    <p>代表者名：上田 敬介</p>
                    <p>設立年月日：2020年6月1日</p>
                </div>
            </div>
            
        </div>

        <div class="row mt-3 mb-2">
            <h3 class="text-center kind faderight">Kind</h3>
        </div>

        <div class="row flexbox">
            <div class="col-md-6 box1 fadeup">
                <div class="">
                    <a href="https://www.field-up.work/energy/" target="_blank"><img class="m-3 d-block mx-auto border border-5 border-danger" src="{% static 'site_app/img/energy_business_rev2.jpg' %}" width="100%"></a>
                </div>
            </div>
            <div class="col-md-6 box2 fadeup">
                <div class="">
                    <a href="https://www.field-up.work/mental_field-up/" target="_blank"><img class="m-3 d-block mx-auto border border-5 border-success" src="{% static 'site_app/img/mental_business_rev2.jpg' %}" width="100%"></a>
                </div>
            </div>
        </div>
        <div class="row flexbox">
            <div class="col-md-6 box1 fadeup">
                <div class="">
                    <a href="https://www.field-up.work/officeinterior/ " target="_blank"><img class="m-3 d-block mx-auto border border-5 border-warning" src="{% static 'site_app/img/construction_business_rev2.jpg' %}" width="100%"></a>
                </div>
            </div>
            <div class="col-md-6 box2 fadeup">
                <div class="">
                    <a href="{% url 'site_app:top' %}"><img class="m-3 d-block mx-auto border border-5 border-info" src="{% static 'site_app/img/system_business_rev1.jpg' %}" width="100%"></a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

Python/field_up/site_app/templates/site_app/header.html
{% load static %}


<div class="row bg-white">
    <div>
    <a href="{% url 'site_app:top' %}"><img class="m-3 sp-logo" als="屋号ロゴ" src="{% static 'site_app/img/logo.png' %}" width="350px"></a>
    {% comment %} <video autoplay muted loop src="{% static 'site_app/img/mini_anime.mp4' %}" width="250px" class="float-end anime01"> {% endcomment %}
        <h1 class="title">
        <span>T</span>
        <span>E</span>
        <span>C</span>
        <span>H</span>
        <span>N</span>
        <span>O</span>
        <span>L</span>
        <span>O</span>
        <span>G</span>
        <span>Y</span>
        {% comment %} <span>&nbsp;</span>
        <span>I</span>
        <span>d</span>
        <span>N</span> {% endcomment %}
        </h1>
    </div>
</div>

<div class="row">
    <nav class="nav-1 bg-info">
    <ul class="bag02">
        <li class="p-3"><a href="{% url 'site_app:company' %}">Company</a></li>
        <li class="p-3 has-child"><a href="#">Content</a>
        <ul>
            <li class="p-1"><a href="{% url 'site_app:appeal' %}">デジタルの魅力</a></li>
            <li class="p-1 has-child"><a href="{% url 'site_app:example' %}">システム開発</a>
            <ul>
                <li class="p-1"><a href="https://www.youtube.com/watch?v=aTx8wclrYVo" target="_blank">映像開発</a></li>
                <li class="p-1"><a href="https://field-up.work/demo_room/main.html" target="_blank">VR開発</a></li>
                <li class=""><a href="https://field-up.work/bound_demo/" target="_blank">簡易ゲーム開発</a></li>
            </ul>
            </li>
            <li class="p-1 has-child"><a href="{% url 'site_app:lang' %}">プログラミング</a>
            <ul>
                <li class="p-1"><a href="{% url 'site_app:vba' %}">VBA</a></li>
                <li class="p-1"><a href="{% url 'site_app:python' %}">Python</a></li>
                <li class="p-1"><a href="{% url 'site_app:java' %}">Java</a></li>
                <li class="p-1"><a href="{% url 'site_app:powerautomate' %}">PowerAutomate</a></li>
                <li class="p-1"><a href="{% url 'site_app:kotlin' %}">Kotlin</a></li>
                <li class="p-1"><a href="{% url 'site_app:css' %}">CSS</a></li>
                <li class="p-1"><a href="{% url 'site_app:php' %}">PHP</a></li>
                <li class="p-1"><a href="{% url 'site_app:swift' %}">Swift</a></li>
                <li class="p-1"><a href="{% url 'site_app:html' %}">HTML</a></li>
                <li class="p-1"><a href="{% url 'site_app:javascript' %}">JavaScript</a></li>
                <li class="p-1"><a href="{% url 'site_app:go' %}">Go</a></li>
                <li class="p-1"><a href="{% url 'site_app:c_sharp' %}">C#</a></li>
            </ul>
            </li>
        </ul>
        </li>
        <li class="p-3"><a href="{% url 'site_app:contacts_faq' %}">Contacts & FAQ</a></li>
    </ul>
    </nav>
</div>